# Automatically
# * determines next version number, based on the commit meesages (feat:/fix:/...)
# * creates a tag + release
# * builds the dll an uploads it to the gh release
name: Autorelease (Build/Tag/Release)
on:
  - push
jobs:
  build:
    uses: informaticon/dev.github.base.pbni-build-action/.github/workflows/pbni-build-action.yml@v2
    with:
      pb_version: "22.0"
      do_release: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/prerelease' }}
    secrets:
      read_token: ${{ secrets.GH_PRIVATE_READ_PAT }}
