# * builds the dll
name: Build
on:
  push:
    branches:
      - '*'
      - '!main'
      - '!prerelease'
jobs:
  build:
    runs-on: [self-hosted, windows]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GH_PRIVATE_READ_PAT }}

      # Needed to give vcpkg access to the private repository
      - name: Git Creds
        run: git config --global url.https://`${{ secrets.GH_PRIVATE_READ_PAT }}@github.com/.insteadOf https://github.com/
        # The backtick ensures, that the secret isn't written into the config file 
        # instead, the token will be expanded when go wants to download a package

      - name: Build
        id: build
        uses: informaticon/dev.github.base.pbni-build-action@v1.3.2